first_number = int(input("Give me the first number: "))
second_number = int(input("Give me the second number: "))
print("Thank you!")
print("%d + %d = %d" % (first_number, second_number, first_number + second_number))
print("%d - %d = %d" % (first_number, second_number, first_number - second_number))
print("%d / %d = %d" % (first_number, second_number, first_number / second_number))
print("%d * %d = %d" % (first_number, second_number, first_number * second_number))